name: MOH Deployment

on: 'push'
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.goblust.com
        username: moh@moh.goblust.com
        password: w![XWlXr0oq?Taur

        
